apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-whaw
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0002-tenant/tkrw-pr712-0075-0002-app/devfile-sample-whaw@sha256:e098a462e8d7ba8ca2088c5a00f72e034336968faa3c9546084e25471ec835f0
        name: my-nodejs
        resources: {}
status: {}
