apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-whaw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-whaw
    app.kubernetes.io/part-of: tkrw-pr712-0075-0002-app
  name: devfile-sample-whaw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-whaw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-whaw
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0002-tenant/tkrw-pr712-0075-0002-app/devfile-sample-whaw@sha256:e098a462e8d7ba8ca2088c5a00f72e034336968faa3c9546084e25471ec835f0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
